version: '2'
services:
    cash-app:
        image: cash
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://cash-mysql:3306/cash?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    cash-mysql:
        extends:
            file: mysql.yml
            service: cash-mysql
